# NOTE: Instructions from https://docs.docker.com/engine/security/rootless/
- name: Install rootless Docker
  hosts: all

  vars_files:
    - "../global_vars.yml"

  tasks:
    - import_tasks: docker.ansible.01_prerequisites.yml
    - import_tasks: docker.ansible.02_install.yml
    - import_tasks: docker.ansible.03_user_setup.yml
    - import_tasks: docker.ansible.04_verify.yml
